### ISSUE TITLE
import errors 

### ISSUE THREAD

**Issue by greenweb** [elidickinson/php-export-data#2]
I get this when attempting to open the generated file in numbers :
<em>Import Warning - This is a tab delimited document, not a valid Excel document. The data might look different.</em>

Google Docs won't import the file due to errors in the file.

I am using your test_tsv_string.php code example to generate the file.

**Comment by elidickinson** [comment]
Not 100% sure I followed that, but it sounds like you're creating a TSV file but saving it with an .XLS file extension. This is a nice trick because lots of spreadsheet apps are set set to associate .XLS files and they can also understand tabbed data... but the problem as you've discovered is you can get scary looking warnings when you open the file.

If you just want to create something that opens in Numbers, I'd suggest a regular CSV:  use the ExportDataCSV class and save the file as a .csv. But note that Numbers probably isn't set to automatically open CSVs. And further, that Excel can do some dumb things with CSV files (like try to "helpfully" convert certain strings to dates).

**Comment by greenweb** [comment]
Thanks for the response, I am doing exactly what you suggested with no issues. 
If you have time I have another question: 
If I use the ExportDataExcel what extension should I save the file out as? I tried . XLS and ran into issues uploading it to Google docs.
